f = open(r'C:\Programs\PREDIX~1\addition.md', 'w', encoding='utf-8') 
f.write('---') 
f.write('\n## Natural Language Explanations') 
f.write('\n### Template-Based Generation') 
f.write('\n```python') 
f.write('class NaturalLanguageExplainer:') 
f.write('    def __init__(self):') 
f.write('        self.templates = {') 
f.write('            \"UP\": {') 
f.write('                \"strong\": \"The model predicts a strong upward move with {prob}% probability. Key drivers: {pos_factors}.\"') 
f.write('                \"moderate\": \"The model indicates a moderate upward bias ({prob}% probability). Supporting factors: {pos_factors}. Caution: {neg_factors}.\"') 
