f = open(r'C:\Programs\PREDIX~1\addition.md', 'w', encoding='utf-8') 
f.write('---') 
f.write('\n## Natural Language Explanations\n') 
f.write('\n### Template-Based Generation\n') 
f.write('\n```python\n') 
